[package]
name = "aoc21-bin"
version = "0.1.0"
edition = "2018"
default-run = "aoc21-bin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc21-lib = { path = "../aoc21-lib" }